echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_pose_publisher-ground_truth_pose_publisher.json -p ./build ./src/auna_ground_truth/src/ground_truth_pose_publisher/ground_truth_pose_publisher.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_pose_publisher-ground_truth_pose_publisher.json -p ./build ./src/auna_ground_truth/src/ground_truth_pose_publisher/ground_truth_pose_publisher.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_transform-ground_truth_transform.json -p ./build ./src/auna_ground_truth/src/ground_truth_transform/ground_truth_transform.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_transform-ground_truth_transform.json -p ./build ./src/auna_ground_truth/src/ground_truth_transform/ground_truth_transform.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_waypoints-src-waypoint_publisher-waypoint_publisher.json -p ./build ./src/auna_waypoints/src/waypoint_publisher/waypoint_publisher.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_waypoints-src-waypoint_publisher-waypoint_publisher.json -p ./build ./src/auna_waypoints/src/waypoint_publisher/waypoint_publisher.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_cam_filter-omnet_cam_filter.json -p ./build ./src/auna_omnet/src/omnet/omnet_cam_filter/omnet_cam_filter.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_cam_filter-omnet_cam_filter.json -p ./build ./src/auna_omnet/src/omnet/omnet_cam_filter/omnet_cam_filter.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_template-src-sample_node-sample_node.json -p ./build ./src/auna_template/src/sample_node/sample_node.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_template-src-sample_node-sample_node.json -p ./build ./src/auna_template/src/sample_node/sample_node.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_transmitter-omnet_transmitter.json -p ./build ./src/auna_omnet/src/omnet/omnet_transmitter/omnet_transmitter.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_transmitter-omnet_transmitter.json -p ./build ./src/auna_omnet/src/omnet/omnet_transmitter/omnet_transmitter.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_cam-ground_truth_cam.json -p ./build ./src/auna_ground_truth/src/ground_truth_cam/ground_truth_cam.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_ground_truth-src-ground_truth_cam-ground_truth_cam.json -p ./build ./src/auna_ground_truth/src/ground_truth_cam/ground_truth_cam.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/physical-ros-g29-force-feedback-src-g29_force_feedback.json -p ./build ./src/physical/ros-g29-force-feedback/src/g29_force_feedback.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/physical-ros-g29-force-feedback-src-g29_force_feedback.json -p ./build ./src/physical/ros-g29-force-feedback/src/g29_force_feedback.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-control_panel.json -p ./build ./src/auna_control/src/control_panel.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-control_panel.json -p ./build ./src/auna_control/src/control_panel.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_f110-src-vesc_start-vesc_start.json -p ./build ./src/auna_f110/src/vesc_start/vesc_start.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_f110-src-vesc_start-vesc_start.json -p ./build ./src/auna_f110/src/vesc_start/vesc_start.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_tf-src-global_tf-global_tf.json -p ./build ./src/auna_tf/src/global_tf/global_tf.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_tf-src-global_tf-global_tf.json -p ./build ./src/auna_tf/src/global_tf/global_tf.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_gazebo-src-robot_name_publisher-robot_name_publisher.json -p ./build ./src/auna_gazebo/src/robot_name_publisher/robot_name_publisher.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_gazebo-src-robot_name_publisher-robot_name_publisher.json -p ./build ./src/auna_gazebo/src/robot_name_publisher/robot_name_publisher.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_receiver-omnet_receiver.json -p ./build ./src/auna_omnet/src/omnet/omnet_receiver/omnet_receiver.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_omnet-src-omnet-omnet_receiver-omnet_receiver.json -p ./build ./src/auna_omnet/src/omnet/omnet_receiver/omnet_receiver.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-cmd_vel_multiplexer_node.json -p ./build ./src/auna_control/src/cmd_vel_multiplexer_node.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-cmd_vel_multiplexer_node.json -p ./build ./src/auna_control/src/cmd_vel_multiplexer_node.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_cacc-src-cacc_controller-cacc_controller.json -p ./build ./src/auna_cacc/src/cacc_controller/cacc_controller.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_cacc-src-cacc_controller-cacc_controller.json -p ./build ./src/auna_cacc/src/cacc_controller/cacc_controller.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_tf-src-localization_pose_publisher-localization_pose_publisher.json -p ./build ./src/auna_tf/src/localization_pose_publisher/localization_pose_publisher.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_tf-src-localization_pose_publisher-localization_pose_publisher.json -p ./build ./src/auna_tf/src/localization_pose_publisher/localization_pose_publisher.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_comm-src-cam_receiver-cam_receiver.json -p ./build ./src/auna_comm/src/cam_receiver/cam_receiver.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_comm-src-cam_receiver-cam_receiver.json -p ./build ./src/auna_comm/src/cam_receiver/cam_receiver.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-control_panel_ros_interface.json -p ./build ./src/auna_control/src/control_panel_ros_interface.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_control-src-control_panel_ros_interface.json -p ./build ./src/auna_control/src/control_panel_ros_interface.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_wallfollowing-src-wallfollowing.json -p ./build ./src/auna_wallfollowing/src/wallfollowing.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_wallfollowing-src-wallfollowing.json -p ./build ./src/auna_wallfollowing/src/wallfollowing.cpp >/dev/null
echo "./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_comm-src-cam_communication-cam_communication.json -p ./build ./src/auna_comm/src/cam_communication/cam_communication.cpp >/dev/null"
./dep-check --extra-arg=-w --extra-arg=-std=c++17 -o /home/ubuntu/workspace/packages/output/auna_comm-src-cam_communication-cam_communication.json -p ./build ./src/auna_comm/src/cam_communication/cam_communication.cpp >/dev/null